# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: alexlevin/ssg-website-test # Replace with your GitHub repo
  branch: main # Or your chosen default branch
  base_url: https://your-auth-worker.workers.dev # Replace with your Cloudflare Worker auth URL

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "yaml"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
